import { Inter } from "next/font/google";
import "./globals.css";
import '@mantine/core/styles.css';

import { MantineProvider } from "@mantine/core";
import { UserProvider } from '@auth0/nextjs-auth0/client';
import Layout from '@/components/appLayout/layout.jsx';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Betel",
  description: "Generated by create next app",
};

function ClientProviders({ children }) {
  return (
    <UserProvider>
      <MantineProvider>{children}</MantineProvider>
    </UserProvider>
  );
}

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <ClientProviders>
          <Layout>{children}</Layout>
        </ClientProviders>
      </body>
    </html>
  );
}
